/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package prototipo.redremover;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int cenario=0x7f020000;
        public static final int cenario2=0x7f020001;
        public static final int face_box=0x7f020002;
        public static final int face_box_tiled=0x7f020003;
        public static final int fase1=0x7f020004;
        public static final int fase10=0x7f020005;
        public static final int fase11=0x7f020006;
        public static final int fase12=0x7f020007;
        public static final int fase2=0x7f020008;
        public static final int fase3=0x7f020009;
        public static final int fase4=0x7f02000a;
        public static final int fase5=0x7f02000b;
        public static final int fase6=0x7f02000c;
        public static final int fase7=0x7f02000d;
        public static final int fase8=0x7f02000e;
        public static final int fase9=0x7f02000f;
        public static final int icon=0x7f020010;
        public static final int intro=0x7f020011;
        public static final int tela=0x7f020012;
    }
    public static final class id {
        public static final int RelativeLayout=0x7f070007;
        public static final int btnJogar=0x7f070008;
        public static final int btnMenu=0x7f070006;
        public static final int btnProxima=0x7f070012;
        public static final int btnSair=0x7f07000a;
        public static final int btnSobre=0x7f070009;
        public static final int btnTentarNovamente=0x7f070005;
        public static final int gridview=0x7f070000;
        public static final int linearLayout1=0x7f07000b;
        public static final int recorde=0x7f070013;
        public static final int refresh=0x7f070014;
        public static final int revert=0x7f070015;
        public static final int tableRow1=0x7f070004;
        public static final int textView1=0x7f07000c;
        public static final int textView2=0x7f07000d;
        public static final int textView3=0x7f07000e;
        public static final int textView4=0x7f07000f;
        public static final int textView5=0x7f070010;
        public static final int textView6=0x7f070011;
        public static final int tvClick=0x7f070002;
        public static final int tvTempo=0x7f070003;
        public static final int tvTitulo=0x7f070001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int telafases=0x7f030001;
        public static final int telalose=0x7f030002;
        public static final int telaprincipal=0x7f030003;
        public static final int telasobre=0x7f030004;
        public static final int telawin=0x7f030005;
    }
    public static final class menu {
        public static final int telamenu=0x7f060000;
    }
    public static final class raw {
        public static final int fase=0x7f040000;
        public static final int knock=0x7f040001;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
}
